version: '3.9'

services:
  db:
    image: postgres
    ports: 
      - "5432:5432"

    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=qwerty

  api:
    build: .
    command: bash -c "make run"

    ports:
      - "8000:8000"
    
    environment:
      - DB_PASS=qwerty
      - DB_USER=testuser
      - DB_HOST=db
      - DB_NAME=testdb
      - DB_PORT=5432
      - DB_ENV=PROD
      - SECRET_KEY=,mwleb;rtjklcwernjtkl3ihcnjkthwjebvj234hiugyvcb5j2345

    depends_on:
      - db
    restart: on-failure:10